# Generated by Django 2.0 on 2018-03-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRecord',
            fields=[
                ('code_key', models.IntegerField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(default='not defined', max_length=100)),
                ('code_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(default='not name', max_length=155)),
                ('goods_spec', models.IntegerField(default=1)),
                ('goods_stock', models.IntegerField(default=0)),
                ('is_recover', models.IntegerField(choices=[(0, '回收'), (1, '不回收')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('store_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=155)),
                ('area_id', models.IntegerField()),
                ('receive_time', models.TimeField(blank=True)),
                ('is_pay', models.IntegerField(default=1)),
                ('pay_from', models.IntegerField(choices=[(0, '现金'), (1, '微信'), (2, '月结'), (3, '未支付')], default=3)),
                ('order_total_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('order_remarks', models.CharField(max_length=155)),
                ('done_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_count', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('session_data', models.CharField(max_length=100, unique=True)),
                ('we_ss_key', models.CharField(max_length=100)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default=0, max_length=155)),
                ('store_phone', models.IntegerField(default=0)),
                ('store_addr', models.CharField(max_length=155)),
                ('store_area', models.IntegerField(default=0)),
                ('store_pay_type', models.IntegerField(choices=[(0, '日结'), (1, '月结')], default=0)),
                ('store_deposit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=155)),
                ('goods_stock', models.IntegerField(default=0)),
                ('goods_spec', models.IntegerField(default=1)),
                ('goods_price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wk', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_type', models.IntegerField(choices=[(0, '管理员'), (1, '库管'), (2, '配送员'), (3, '顾客'), (4, '未注册')], default=4, verbose_name='用户身份')),
                ('nick_name', models.CharField(default='nick_name', max_length=100)),
                ('avatar_links', models.CharField(default='https://pic3.zhimg.com/aadd7b895_s.jpg', max_length=150)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('wk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.User')),
                ('area_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('wk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.User')),
                ('store_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
