# Generated by Django 2.0 on 2018-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180302_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receive_time',
        ),
        migrations.AddField(
            model_name='order',
            name='is_receive',
            field=models.IntegerField(choices=[(0, '已送到'), (1, '未送到')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
