# Generated by Django 2.0 on 2018-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180302_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
