# Generated by Django 2.0 on 2018-03-08 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180307_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 21, 25, 32, 158320)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_spec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='goods_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='store_id',
            field=models.IntegerField(blank=True),
        ),
    ]
