# Generated by Django 2.0 on 2018-03-19 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180308_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_pay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_receive',
        ),
        migrations.RemoveField(
            model_name='storegoods',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='storegoods',
            name='goods_spec',
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='name',
            field=models.CharField(default='peisong_name', max_length=50),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(0, '已完成'), (1, '待支付'), (2, '待送达'), (3, '已取消')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '日结'), (1, '月结')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.IntegerField(choices=[[2, 'test_store_1'], [3, 'test_store_2'], [4, 'test_store_3'], [5, 'Auto_test_store_1'], [10574, 'Auto_test_store_2'], [14306, 'Auto_test_store_2'], [16443, 'Auto_test_store_2'], [21865, 'Auto_test_store_2'], [23911, 'Auto_test_store_2'], [24665, 'Auto_test_store_2'], [24681, 'Auto_test_store_2'], [24737, 'Auto_test_store_2'], [27143, 'Auto_test_store_2'], [28530, 'Auto_test_store_2'], [42494, 'Auto_test_store_2'], [43752, 'Auto_test_store_2'], [44742, 'Auto_test_store_2'], [44785, 'Auto_test_store_2'], [45090, 'Auto_test_store_2'], [46069, 'Auto_test_store_2'], [47068, 'Auto_test_store_2'], [47492, 'Auto_test_store_2'], [49407, 'Auto_test_store_2'], [50234, 'Auto_test_store_2'], [53075, 'Auto_test_store_2'], [54192, 'Auto_test_store_2'], [55450, 'Auto_test_store_2'], [56943, 'Auto_test_store_2'], [57770, 'Auto_test_store_2'], [59662, 'Auto_test_store_2'], [60385, 'Auto_test_store_2'], [60832, 'Auto_test_store_2'], [64602, 'Auto_test_store_2'], [66576, 'Auto_test_store_2'], [67061, 'Auto_test_store_2'], [67947, 'Auto_test_store_2'], [69425, 'Auto_test_store_2'], [69901, 'Auto_test_store_2'], [76709, 'Auto_test_store_2'], [80025, 'Auto_test_store_2'], [81476, 'Auto_test_store_2'], [82323, 'Auto_test_store_2'], [82968, 'Auto_test_store_2'], [83290, 'Auto_test_store_2'], [86071, 'Auto_test_store_2'], [86375, 'store_1'], [92180, 'Auto_test_store_2'], [92321, 'Auto_test_store_2'], [92417, 'Auto_test_store_2'], [92608, 'Auto_test_store_2'], [96375, 'Auto_test_store_2'], [97157, 'Auto_test_store_2'], [97436, 'store_1']]),
        ),
        migrations.AlterField(
            model_name='session',
            name='we_ss_key',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_addr',
            field=models.CharField(default='无', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_area',
            field=models.IntegerField(choices=[[2, 'test_area_1'], [3, 'test_area_2'], [4, 'test_area_3'], [5, 'test_area_4'], [6, 'test_area_5']], default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='goods_id',
            field=models.IntegerField(blank=True, choices=[[1, '2件套'], [2, '2件套'], [3, '2件套'], [4, '2件套'], [5, '3件套'], [6, '3件套'], [7, '一次性 筷子'], [8, '专版筷子']]),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='store_id',
            field=models.IntegerField(blank=True, choices=[[2, 'test_store_1'], [3, 'test_store_2'], [4, 'test_store_3'], [5, 'Auto_test_store_1'], [10574, 'Auto_test_store_2'], [14306, 'Auto_test_store_2'], [16443, 'Auto_test_store_2'], [21865, 'Auto_test_store_2'], [23911, 'Auto_test_store_2'], [24665, 'Auto_test_store_2'], [24681, 'Auto_test_store_2'], [24737, 'Auto_test_store_2'], [27143, 'Auto_test_store_2'], [28530, 'Auto_test_store_2'], [42494, 'Auto_test_store_2'], [43752, 'Auto_test_store_2'], [44742, 'Auto_test_store_2'], [44785, 'Auto_test_store_2'], [45090, 'Auto_test_store_2'], [46069, 'Auto_test_store_2'], [47068, 'Auto_test_store_2'], [47492, 'Auto_test_store_2'], [49407, 'Auto_test_store_2'], [50234, 'Auto_test_store_2'], [53075, 'Auto_test_store_2'], [54192, 'Auto_test_store_2'], [55450, 'Auto_test_store_2'], [56943, 'Auto_test_store_2'], [57770, 'Auto_test_store_2'], [59662, 'Auto_test_store_2'], [60385, 'Auto_test_store_2'], [60832, 'Auto_test_store_2'], [64602, 'Auto_test_store_2'], [66576, 'Auto_test_store_2'], [67061, 'Auto_test_store_2'], [67947, 'Auto_test_store_2'], [69425, 'Auto_test_store_2'], [69901, 'Auto_test_store_2'], [76709, 'Auto_test_store_2'], [80025, 'Auto_test_store_2'], [81476, 'Auto_test_store_2'], [82323, 'Auto_test_store_2'], [82968, 'Auto_test_store_2'], [83290, 'Auto_test_store_2'], [86071, 'Auto_test_store_2'], [86375, 'store_1'], [92180, 'Auto_test_store_2'], [92321, 'Auto_test_store_2'], [92417, 'Auto_test_store_2'], [92608, 'Auto_test_store_2'], [96375, 'Auto_test_store_2'], [97157, 'Auto_test_store_2'], [97436, 'store_1']]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
