# Generated by Django 2.0 on 2018-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20180319_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.IntegerField(choices=[[2, 'test_store_1'], [3, 'test_store_2'], [4, 'test_store_3'], [5, 'Auto_test_store_1'], [10574, 'Auto_test_store_2'], [14306, 'Auto_test_store_2'], [16443, 'Auto_test_store_2'], [21865, 'Auto_test_store_2'], [23911, 'Auto_test_store_2'], [24665, 'Auto_test_store_2'], [24681, 'Auto_test_store_2'], [24737, 'Auto_test_store_2'], [27143, 'Auto_test_store_2'], [28247, 'store_Auto_Store4'], [28530, 'Auto_test_store_2'], [35333, 'TEST_AUTO_NAME'], [42494, 'Auto_test_store_2'], [43752, 'Auto_test_store_2'], [44742, 'Auto_test_store_2'], [44785, 'Auto_test_store_2'], [45090, 'Auto_test_store_2'], [46069, 'Auto_test_store_2'], [47068, 'Auto_test_store_2'], [47492, 'Auto_test_store_2'], [49407, 'Auto_test_store_2'], [50234, 'Auto_test_store_2'], [53075, 'Auto_test_store_2'], [54192, 'Auto_test_store_2'], [55450, 'Auto_test_store_2'], [56943, 'Auto_test_store_2'], [57770, 'Auto_test_store_2'], [59662, 'Auto_test_store_2'], [60385, 'Auto_test_store_2'], [60832, 'Auto_test_store_2'], [62355, 'TEST_AUTO_NAME'], [64602, 'Auto_test_store_2'], [66576, 'Auto_test_store_2'], [67061, 'Auto_test_store_2'], [67947, 'Auto_test_store_2'], [69425, 'Auto_test_store_2'], [69747, 'TEST_AUTO_NAME'], [69901, 'Auto_test_store_2'], [76709, 'Auto_test_store_2'], [80025, 'Auto_test_store_2'], [81476, 'Auto_test_store_2'], [82323, 'Auto_test_store_2'], [82968, 'Auto_test_store_2'], [83290, 'Auto_test_store_2'], [86071, 'Auto_test_store_2'], [86375, 'store_1'], [89966, 'TEST_AUTO_NAME'], [92180, 'Auto_test_store_2'], [92321, 'Auto_test_store_2'], [92417, 'Auto_test_store_2'], [92608, 'Auto_test_store_2'], [96375, 'Auto_test_store_2'], [97157, 'Auto_test_store_2'], [97436, 'store_1']]),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_area',
            field=models.IntegerField(choices=[[2, 'test_area_1'], [3, 'test_area_2'], [4, 'test_area_3'], [5, 'test_area_4'], [15, 'test_area_5'], [22, 'AUTO_TEST_AREA_1']], default=0),
        ),
        migrations.AlterField(
            model_name='storegoods',
            name='store_id',
            field=models.IntegerField(blank=True, choices=[[2, 'test_store_1'], [3, 'test_store_2'], [4, 'test_store_3'], [5, 'Auto_test_store_1'], [10574, 'Auto_test_store_2'], [14306, 'Auto_test_store_2'], [16443, 'Auto_test_store_2'], [21865, 'Auto_test_store_2'], [23911, 'Auto_test_store_2'], [24665, 'Auto_test_store_2'], [24681, 'Auto_test_store_2'], [24737, 'Auto_test_store_2'], [27143, 'Auto_test_store_2'], [28247, 'store_Auto_Store4'], [28530, 'Auto_test_store_2'], [35333, 'TEST_AUTO_NAME'], [42494, 'Auto_test_store_2'], [43752, 'Auto_test_store_2'], [44742, 'Auto_test_store_2'], [44785, 'Auto_test_store_2'], [45090, 'Auto_test_store_2'], [46069, 'Auto_test_store_2'], [47068, 'Auto_test_store_2'], [47492, 'Auto_test_store_2'], [49407, 'Auto_test_store_2'], [50234, 'Auto_test_store_2'], [53075, 'Auto_test_store_2'], [54192, 'Auto_test_store_2'], [55450, 'Auto_test_store_2'], [56943, 'Auto_test_store_2'], [57770, 'Auto_test_store_2'], [59662, 'Auto_test_store_2'], [60385, 'Auto_test_store_2'], [60832, 'Auto_test_store_2'], [62355, 'TEST_AUTO_NAME'], [64602, 'Auto_test_store_2'], [66576, 'Auto_test_store_2'], [67061, 'Auto_test_store_2'], [67947, 'Auto_test_store_2'], [69425, 'Auto_test_store_2'], [69747, 'TEST_AUTO_NAME'], [69901, 'Auto_test_store_2'], [76709, 'Auto_test_store_2'], [80025, 'Auto_test_store_2'], [81476, 'Auto_test_store_2'], [82323, 'Auto_test_store_2'], [82968, 'Auto_test_store_2'], [83290, 'Auto_test_store_2'], [86071, 'Auto_test_store_2'], [86375, 'store_1'], [89966, 'TEST_AUTO_NAME'], [92180, 'Auto_test_store_2'], [92321, 'Auto_test_store_2'], [92417, 'Auto_test_store_2'], [92608, 'Auto_test_store_2'], [96375, 'Auto_test_store_2'], [97157, 'Auto_test_store_2'], [97436, 'store_1']]),
        ),
    ]
